stages:
  - deploy

deploy_minikube:
  stage: deploy
  script:
    - export MINIKUBE_VERSION=v1.23.2  # Update with the desired Minikube version
    - curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBE_VERSION/minikube-linux-amd64
    - chmod +x minikube
    - sudo mv minikube /usr/local/bin/
    - minikube start
    # Add any additional Minikube setup or deployment steps here
  only:
    - main
